/** HMAC signing for the /feedback endpoint.
 *
 * The backend requires requests to /feedback to carry an HMAC-SHA256
 * signature of the payload (message_id|rating|timestamp) keyed by the
 * API key. This prevents replay attacks and proves the request was
 * generated by the official frontend.
 *
 * Uses the Web Crypto API (available in all modern browsers).
 */

const API_KEY = import.meta.env.VITE_CHAT_API_KEY ?? ""

export async function signFeedback(
  messageId: string,
  rating: "up" | "down",
): Promise<{ timestamp: string; signature: string }> {
  const timestamp = Math.floor(Date.now() / 1000).toString()
  const payload = `${messageId}|${rating}|${timestamp}`

  const encoder = new TextEncoder()
  const keyData = encoder.encode(API_KEY)
  const cryptoKey = await crypto.subtle.importKey(
    "raw",
    keyData,
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  )
  const sigBuf = await crypto.subtle.sign(
    "HMAC",
    cryptoKey,
    encoder.encode(payload),
  )
  const signature = Array.from(new Uint8Array(sigBuf))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("")

  return { timestamp, signature }
}

export async function submitFeedback(
  messageId: string,
  rating: "up" | "down",
): Promise<boolean> {
  const { timestamp, signature } = await signFeedback(messageId, rating)
  try {
    const res = await fetch("/api/feedback", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-API-Key": API_KEY,
      },
      body: JSON.stringify({ message_id: messageId, rating, timestamp, signature }),
    })
    return res.ok
  } catch {
    return false
  }
}
